version: '2'
services:
    jh-app:
        image: jh
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jh-mysql:3306/jh?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jh-mysql:
        extends:
            file: mysql.yml
            service: jh-mysql
